apiVersion: v1
kind: Secret
metadata:
  namespace: n8n-ns
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: db_admin
  POSTGRES_PASSWORD: db_password
  POSTGRES_DB: n8n-db
  POSTGRES_NON_ROOT_USER: n8n_user
  POSTGRES_NON_ROOT_PASSWORD: n8n_password

